env: local

server:
  port: "8081"

postgres:
  host: postgres
  port: "5432"
  username: postgres
  password: ""
  dbname: postgres
  sslmode: disable

kafka:
  brokers:
    - "localhost:9092"
  topic: "orders"
  group_id: "order-service-group"

migrations: "./migrations"