env: local

server:
  port: "8080"

postgres:
  host: "localhost"
  port: "5432"
  username: "app_user"
  dbname: "orders_db"
  sslmode: "disable"

kafka:
  brokers:
    - "localhost:9092"
  topic: "orders"
  group_id: "order-service-group"

migrations: "./migrations"